services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "127.0.0.1:9080:9080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - micro-net

networks:
  micro-net:
    external: true